### ISSUE TITLE
TODO: trajectory_generator branch

### ISSUE THREAD

**Issue by huckl3b3rry87** [huckl3b3rry87/Autoware#2]
- [ ] Initialize with a particular case using yaml config file, get rid of CaseModule initialization in MAVs
- [ ] Read new obstacle information data from a particular message and update optimization accordingly
- [ ] Read new vehicle state from a particular message and update optimization accordingly

**Comment by huckl3b3rry87** [comment]
The first task is nearly completed with https://github.com/huckl3b3rry87/MAVs.jl/tree/feature/yaml. A few things still need to be tested and developed and then it can be merged into the master

**Comment by huckl3b3rry87** [comment]
moved to Autoware
